# -*- coding: utf-8 -*-
"""AKorepanova_inbank_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IorR-32wbEeLUCXkdbextiagZ2p9IZFa

In order to fulfill regulatory requirements, I-bank is obliged to provide aggregated daily report to B-Authority. It’s been agreed that during workdays, reports should be provided daily by 5 pm at latest. However, the agreement for weekends is different - due to regular scheduled maintenance of B-Authority servers, data for Saturday and Sunday should be aggregated and sent out in one file on Monday mornings.

**Input:** 2 csv files with aggregated data for Saturday and Sunday.
**Output:** 1 csv file with Saturday and Sunday data combined.
**Task:** please write a Python script that would combine data from 2 files (archive with files available in GitHub) into one. Overall file structure could be preserved - but add information about combined file generation date (in additional column).
"""

import pandas as pd
import io
from google.colab import files
import datetime

# this is how you input data if you run the script locally (Jupyter, Spyder, etc.)
# insert files pathnames in ''
#df1 = pd.read_csv('/Users/CUDAN/Documents/python notebooks/inbank test/weekend_data_processing/data_2023-02-11.csv', sep = ';')
#df2 = pd.read_csv('/Users/CUDAN/Documents/python notebooks/inbank test/weekend_data_processing/data_2023-02-12.csv', sep = ';')

# uploadng data to colab from your computer
uploaded = files.upload ()
df1 = pd.read_csv(io.BytesIO(uploaded['data_2023-02-11.csv']), sep = ';')
uploaded = files.upload ()
df2 = pd.read_csv(io.BytesIO(uploaded['data_2023-02-12.csv']), sep = ';')

df1

df2

# Combining datasets into one dataframe
df_combined = pd.concat([df1, df2])

# Adding a new column with the generation date
df_combined['file_creation_date'] = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Saving the combined df to a new CSV file
df_combined.to_csv('sat_and_sun_data.csv', index=False)

df_combined